
services:
  db:
    image: postgres:15-alpine
    container_name: shield_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anjalipost
      POSTGRES_DB: shield_api_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: